#!/bin/sh

# Check if a directory exists, and if it does not then create the ocmplete directory path
# !!! This function is needed for shell initialization !!!
#     Specificially, ewhd-env is dependent on it
ensure_dir_exists() {
    local directory_path="$1"
    if [ ! -d "$directory_path" ]; then
        mkdir -p "$directory_path"
    fi
}


# Streamlined cd alternative
# from: https://superuser.com/a/1244522
c() {
  if [ -n "$1" ]; then
    cd "$1" || return 1
  else
    cd ..
  fi
  ll
}
ll() ( ls -hl --time-style="+%Y-%m-%d_%H:%M:%S" "$@"; )



#EOF
