#!/bin/sh

# this is a file of all my custom environment variables and path additions

# Source custom shell functions (needed for at least the ensure_dir_exists function, which is used by this and other environment setting configs)
if [ -f $HOME/.config/ewhd/ewhd-shell-functions ]
then
    . $HOME/.config/ewhd/ewhd-shell-functions
else
    printf "WARNING: custom shell functions file (ewhd-shell-functions) not found\nSome things may not work as expected\n" > /dev/stderr
fi



#### XDG Base Directories:
## set the variables, then create the directories if they don't exist
export XDG_CONFIG_HOME=$HOME/.config && ensure_dir_exists $XDG_CONFIG_HOME
export XDG_CACHE_HOME=$HOME/.cache && ensure_dir_exists $XDG_CACHE_HOME
export XDG_DATA_HOME=$HOME/.local/share && ensure_dir_exists $XDG_DATA_HOME
export XDG_STATE_HOME=$HOME/.local/state && ensure_dir_exists $XDG_STATE_HOME


#### XDG Environment Variable to Simplify $HOME
## Mostly suggested by xdg_ninja.sh
## set the variables, then create the directories if they don't exist
export HISTFILE="${XDG_STATE_HOME}"/bash/history && ensure_dir_exists $HISTFILE
export LESSHISTFILE="$XDG_STATE_HOME"/less/history && ensure_dir_exists $LESSHISTFILE
export ZDOTDIR="$HOME"/.config/zsh && ensure_dir_exists $ZDOTDIR
#export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority && ensure_dir_exists $XAUTHORITY  # causes auth problems with xrdp


# Avoid loading Ranger config twice:
export RANGER_LOAD_DEFAULT_RC=FALSE


#### Path Additions:

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# set PATH so it includes user's custom scripts if it exists
if [ -d "$XDG_CONFIG_HOME/scripts" ] ; then
    PATH="$XDG_CONFIG_HOME/scripts:$PATH"
fi

# Force Anki to run on Wayland:
export ANKI_WAYLAND=1


#EOF
