#!/bin/sh

# this is a file of all my custom environment variables and path additions

# Source custom shell functions (needed for at least the ensure_dir_exists function, which is used by this and other environment setting configs)
if [ -f $HOME/.config/ewhd/ewhd-shell-functions ]
then
    . $HOME/.config/ewhd/ewhd-shell-functions
else
    printf "WARNING: custom shell functions file (ewhd-shell-functions) not found\nSome things may not work as expected\n" > /dev/stderr
fi



#### XDG Base Directories:
## set the variables, then create the directories if they don't exist
export XDG_CONFIG_HOME=$HOME/.config && ensure_dir_exists $XDG_CONFIG_HOME
export XDG_CACHE_HOME=$HOME/.cache && ensure_dir_exists $XDG_CACHE_HOME
export XDG_DATA_HOME=$HOME/.local/share && ensure_dir_exists $XDG_DATA_HOME
export XDG_STATE_HOME=$HOME/.local/state && ensure_dir_exists $XDG_STATE_HOME


#### XDG Environment Variable to Simplify $HOME
## Mostly suggested by xdg_ninja.sh
## set the variables, then create the directories if they don't exist
export HISTFILE="${XDG_STATE_HOME}"/bash/history && ensure_dir_exists $HISTFILE
export LESSHISTFILE="$XDG_STATE_HOME"/less/history && ensure_dir_exists $LESSHISTFILE
export ZDOTDIR="$HOME"/.config/zsh && ensure_dir_exists $ZDOTDIR
#export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority && ensure_dir_exists $XAUTHORITY  # causes auth problems with xrdp


# Avoid loading Ranger config twice:
export RANGER_LOAD_DEFAULT_RC=FALSE


#### Path Additions:

add_to_path() {
    for dir in "$@"; do
        if [ -d "$dir" ] && [[ ":$PATH:" != *":$dir:"* ]]; then
            PATH="$dir:$PATH"
        fi
    done

    # De-duplication (removes all redundant entries, preserving the earliest)
    export PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=':' '!seen[$0]++' | sed 's/:$//')
}

add_to_path "$HOME/bin" "$HOME/.local/bin" "/sbin" "/usr/sbin" "/usr/local/sbin"


# Force Anki to run on Wayland:
export ANKI_WAYLAND=1


#EOF
