#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init



# if my custom environment variables file exists, source it:
if [ -f $HOME/.config/ewhd/ewhd-env ]
then
    printf "Sourcing custom environment settings...\n"
    . $HOME/.config/ewhd/ewhd-env
else
    printf "WARNING: custom environment settings file (~/config/ewhd/ewhd-env) not found\nSome things may not work as expected\n" > /dev/stderr
fi



# if my custom install script exists, attempt to execute it with sudo privileges:
if [ -f $HOME/.config/ewhd/install-script.sh ]
then
    printf "Custom install script found--executing with sudo privileges:\n"
    sudo $HOME/.config/ewhd/install-script.sh
else
    printf "WARNING: custom install script (~/config/ewhd/install-script.sh) not found\nSome things may not work as expected\n" > /dev/stderr
fi
